import "./AllProjects.css";
import ProjectBox from "../../Components/ProjectBox/ProjectBox";
import { Link } from "react-router-dom";
import { useTheme } from "../../ThemeContext";

const AllProjects = () => {

    const { theme } = useTheme();
    const { toggleTheme } = useTheme();

    return(
        <div>
            <section className="container-portfolio">
            <Link to="/">
                <h4 className="back-home"> <span className="arrow-back"> - </span> Voltar ao início</h4>
            </Link>
            <h2>Todos os projetos</h2>
            <div className="all-portfolio">
            <ProjectBox ImgProject={"projeto-afroglow.png"} NameProject={"AfroGlow"} DescriptionProject={"A AfroGlow visa fortalecer a autoestima de crianças com cabelos afro, proporcionando autoestima e um forte sentimento de pertencimento."} SkillsProject1={"Figma"} SkillsProject2={"React/CSS"} SkillsProject3={"Bootstrap"} SkillsProject4={"Java/Spring"} SkillsProject5={"SQL"} SiteProject={"https://www.afroglow.com.br/"} GithubProject={"https://github.com/AfroGlow/PlataformaAfroGlow?tab=readme-ov-file"} GithubProject2={"https://github.com/AfroGlow/BackendAfroGlow"} FigmaProject={"https://www.figma.com/file/tmMpKY6U0T90iErD8FBUMQ/AfroGlow?type=design&node-id=111%3A3&mode=design&t=f3EANUKr8BZomecZ-1"}/>
            <ProjectBox ImgProject={"projeto-clone-netflix.png"} NameProject={"Clone Netflix"} DescriptionProject={"Este é um projeto que representa o clone da landing page da Netflix. Podemos observar que ficou idêntico, o layout ficou lindo, e chama muita atenção."} SkillsProject1={"React"} SkillsProject2={"CSS"} SkillsProject3={null} SkillsProject4={null} SkillsProject5={null} SiteProject={"https://clone-netflix-nine-chi.vercel.app/"} GithubProject={"https://github.com/Lilian-Carvalho25/Clone-Netflix"} GithubProject2={null} FigmaProject={null}/>
            <ProjectBox ImgProject={"projeto-organo.png"} NameProject={"Organo"} DescriptionProject={"O Organo representa um site simples, onde utilizei um design minimalista mas delicado, e os colaboradores podem ser cadastrados de maneira simples."} SkillsProject1={"React"} SkillsProject2={"CSS"} SkillsProject3={null} SkillsProject4={null} SkillsProject5={null} SiteProject={"https://organo-mocha-theta.vercel.app/"} GithubProject={"https://github.com/Lilian-Carvalho25/organo"} GithubProject2={null} FigmaProject={null}/>
            <ProjectBox ImgProject={"projeto-nutriacess.png"} NameProject={"NutriAcess"} DescriptionProject={"A Nutriacess é uma plataforma desenvolvida com o objetivo de democratizar o acesso a consultas nutricionais de forma acessível."} SkillsProject1={"Figma"} SkillsProject2={"React"} SkillsProject3={"Typescript"} SkillsProject4={"MySQL"} SkillsProject5={"Node"} SiteProject={"http://nutriacess.com.br/"} GithubProject={"https://github.com/Lilian-Carvalho25/front-nutriacess"} GithubProject2={"https://github.com/NutriAcess/NutriAcess_Back-end"} FigmaProject={"https://www.figma.com/file/FNNHvyBxXBNVziRP1AKOd8/Nutriacess%2Fdesktop?type=design&node-id=0%3A1&mode=design&t=pyNbpWf6XgsbzeO5-1"}/>
            <ProjectBox ImgProject={"projeto-brasa-divina.png"} NameProject={"Brasa divina"} DescriptionProject={"Brasa divina é um exemplo de site para uma pizzaria real. Nele, o usuário tem a opção de selecionar opções prontas, ou montar sua própria pizza."} SkillsProject1={"Figma"} SkillsProject2={"HTML/CSS"} SkillsProject3={"JS"} SkillsProject4={"MySQL"} SkillsProject5={"PHP"} SiteProject={"http://brasa-divina.x10.mx/index.php"} GithubProject={"https://github.com/AfroGlow/PlataformaAfroGlow?tab=readme-ov-file"} GithubProject2={null}  FigmaProject={"https://www.figma.com/file/cTKmShxHOqdVNfJ2HXuXdy/Brasa-Divina?type=design&node-id=0%3A1&mode=design&t=GIjG3NN5jcoHcEhc-1"}/>
            <ProjectBox ImgProject={"projeto-doe-e-alimente.png"} NameProject={"Doe e alimente"} DescriptionProject={"O objetivo principal da Doe e alimente é redirecionar doações em dinheiro para projetos e ONGs focados na luta contra a fome no Brasil."} SkillsProject1={"HTML/CSS"} SkillsProject2={"JS"} SkillsProject3={"Bootstrap"} SkillsProject4={"MySQL"} SkillsProject5={"PHP"} SiteProject={"http://dooe-e-alimente.x10.mx/index.php"} GithubProject={"https://github.com/Lilian-Carvalho25/Doe-e-alimente"} GithubProject2={null} FigmaProject={null}/>
            <ProjectBox ImgProject={"projeto-microblog.png"} NameProject={"Microblog"} DescriptionProject={"O Microblog é um site dinâmico de notícias, onde o usuário pode inserir, atualizar e excluir notícias e perfis de usuário."} SkillsProject1={"Bootstrap"} SkillsProject2={"JS"} SkillsProject3={"MySQL"} SkillsProject4={"PHP"} SkillsProject5={null} SiteProject={"http://microblog-lilian.x10.mx/index.php"} GithubProject={"https://github.com/Lilian-Carvalho25/microblog-inicial"} GithubProject2={null} FigmaProject={null}/>
            <ProjectBox ImgProject={"projeto-joguinho.png"} NameProject={"Joguinho Nutriacess"} DescriptionProject={"Este é um jogo simples, desenvolvido para a NutriAcess. Neste jogo, o usuário pode interagir com a Lilian, a avatar do projeto, de uma forma dinâmica."} SkillsProject1={"HTML"} SkillsProject2={"CSS"} SkillsProject3={"JS"} SkillsProject4={null} SkillsProject5={null} SiteProject={"https://joguinho-nutriacess.vercel.app/index.html"} GithubProject={"https://github.com/Lilian-Carvalho25/joguinho-nutriacess"} GithubProject2={null} FigmaProject={null}/>
            <ProjectBox ImgProject={"projeto-buscador.png"} NameProject={"Buscador de CEP"} DescriptionProject={"Aqui, temos um buscador de CEP com um layout muito bonito, bem constuído e intuitivo, onde usei a biblioteca de Javascript, o JQuery."} SkillsProject1={"HTML"} SkillsProject2={"CSS"} SkillsProject3={"JS"} SkillsProject4={"JQuery"} SkillsProject5={null} SiteProject={"https://lilian-carvalho25.github.io/buscador-de-cep/"} GithubProject={"https://github.com/Lilian-Carvalho25/buscador-de-cep"} GithubProject2={null} FigmaProject={null}/>
            <ProjectBox ImgProject={"projeto-honeyshop.png"} NameProject={"HoneyShop"} DescriptionProject={"Esta é uma landing page muito bonita, para uma lojinha de mel, que chama bastante atenção. Fiz esse projeto no intuito de praticar."} SkillsProject1={"HTML"} SkillsProject2={"CSS"} SkillsProject3={null} SkillsProject4={null} SkillsProject5={null} SiteProject={"https://lilian-carvalho25.github.io/HoneyShop/"} GithubProject={"https://github.com/Lilian-Carvalho25/HoneyShop"} GithubProject2={null} FigmaProject={null}/>
            <ProjectBox ImgProject={"projeto-fuitopia.png"} NameProject={"Fruitopia"} DescriptionProject={"Fruitopia é uma landing page linda, e o objetivo dela é chamar o público, para comprar os morangos oferecidos para compra"} SkillsProject1={"HTML"} SkillsProject2={"CSS"} SkillsProject3={null} SkillsProject4={null} SkillsProject5={null} SiteProject={"https://lilian-carvalho25.github.io/fruitopia/"} GithubProject={"https://github.com/Lilian-Carvalho25/fruitopia"} GithubProject2={null} FigmaProject={null}/>
            <ProjectBox ImgProject={"projeto-simplicity.png"} NameProject={"Simplicity"} DescriptionProject={"Bem vindo(a) ao meu primeiro projeto front-end!. Neste projeto, aprendi muito sobre a estrutura de páginas,  boas práticas etc."} SkillsProject1={"HTML"} SkillsProject2={"CSS"} SkillsProject3={"JS"} SkillsProject4={"JQuery"} SiteProject={"https://lilian-carvalho25.github.io/simplicity/"} GithubProject={"https://github.com/Lilian-Carvalho25/simplicity"} GithubProject2={null} FigmaProject={null}/>
            <ProjectBox ImgProject={"projeto-petruccio.png"} NameProject={"Petruccio"} DescriptionProject={"Este projeto representa uma pizzaria linda e aconchegante, onde as informações estão dispostas de uma forma suave e intuitiva."} SkillsProject1={"HTML"} SkillsProject2={"CSS"} SkillsProject3={"JS"} SkillsProject4={null} SkillsProject5={null} SiteProject={"https://lilian-carvalho25.github.io/Pizzaria-petruccio/"} GithubProject={"https://github.com/Lilian-Carvalho25/Pizzaria-petruccio"} GithubProject2={null} FigmaProject={null}/>
            <ProjectBox ImgProject={"projeto-quispy.png"} NameProject={"Qrispy"} DescriptionProject={"Aqui, vemos uma representação de um restaurante, onde o usuário tem diversas opções de pratos para escolher, além de verificar outras informações."} SkillsProject1={"HTML"} SkillsProject2={"CSS"} SkillsProject3={"Bootstrap"} SkillsProject4={null} SkillsProject5={null} SiteProject={"https://lilian-carvalho25.github.io/Qrispy/"} GithubProject={"https://github.com/Lilian-Carvalho25/Qrispy"} GithubProject2={null} FigmaProject={null}/>
            <ProjectBox ImgProject={"projeto-florestas.png"} NameProject={"Florestas do mundo"} DescriptionProject={"As florestas do mundo são sensacionais, você não acha? Este trabalho mostra um pouco das florestas do meu coração. Conheça os caminhos  da exploração!"} SkillsProject1={"HTML"} SkillsProject2={"CSS"} SkillsProject3={"JS"} SkillsProject4={"Bootstrap"} SkillsProject5={null} SiteProject={"https://lilian-carvalho25.github.io/florestas-do-mundo/"} GithubProject={"https://github.com/Lilian-Carvalho25/florestas-do-mundo"} GithubProject2={null} FigmaProject={null}/>
            </div>
            <h2>Especiais Figma</h2>
            <div className="all-portfolio">
            <ProjectBox ImgProject={"projeto-inspiracao.png"} NameProject={"Tributo"} DescriptionProject={"Neste projeto, eu fiz um tributo a três mulheres negras potentes, que contribuem muito com a nossa cultura e desenvolvimento."} SkillsProject1={null} SkillsProject2={null} SkillsProject3={null} SkillsProject4={null} SkillsProject5={null} SiteProject={"https://www.figma.com/proto/sNxizQnuhLI1aYlW77nHD9/Inspira%C3%A7%C3%A3o?type=design&node-id=9-17&t=LwwsGbaYgquMUl5K-0&scaling=scale-down&page-id=0%3A1&starting-point-node-id=9%3A17"} GithubProject={null} GithubProject2={null} FigmaProject={"https://www.figma.com/file/sNxizQnuhLI1aYlW77nHD9/Inspira%C3%A7%C3%A3o?type=design&node-id=0%3A1&mode=design&t=LwwsGbaYgquMUl5K-1"}/>
            <ProjectBox ImgProject={"projeto-musicas.png"} NameProject={"Daccord"} DescriptionProject={"Este projeto representa a landing page de um site de músicas, onde temos o menu a esquerda, os destaques no centro e as atualizações a direita."} SkillsProject1={null} SkillsProject2={null} SkillsProject3={null} SkillsProject4={null} SkillsProject5={null} SiteProject={"https://www.figma.com/proto/ZoZ3zR2vtakrYblDpEdszA/Projeto-final?type=design&node-id=1-208&t=gszZY0vE0wYyIGg3-0&scaling=min-zoom&page-id=0%3A1"} GithubProject={null} GithubProject2={null} FigmaProject={"https://www.figma.com/file/ZoZ3zR2vtakrYblDpEdszA/Projeto-final?type=design&node-id=0%3A1&mode=design&t=gszZY0vE0wYyIGg3-1"}/>
            <ProjectBox ImgProject={"projeto-bike.png"} NameProject={"Loja de bicicletas"} DescriptionProject={"Esta é uma simulação de como seria feita a compra de uma bicicleta através de um site, com desconto. O protótipo conta com interações muito divertidas."} SkillsProject1={null} SkillsProject2={null} SkillsProject3={null} SkillsProject4={null} SkillsProject5={null} SiteProject={"https://www.figma.com/proto/DI2MeiwSIXFHSNbwhcrz5D/Atividade02?type=design&node-id=1-2450&t=2yCl5W5whFCdgGIW-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2450"} GithubProject={null} GithubProject2={null} FigmaProject={"https://www.figma.com/file/DI2MeiwSIXFHSNbwhcrz5D/Atividade02?type=design&node-id=0%3A1&mode=design&t=2yCl5W5whFCdgGIW-1"}/>
            <ProjectBox ImgProject={"projeto-tenis.png"} NameProject={"Loja de tênis"} DescriptionProject={"Aqui, temos uma loja que vende tênis, onde você encontra algumas opções na home, e pode saber mais sobre o produto quando clica nele, além de ver suas fotos."} SkillsProject1={null} SkillsProject2={null} SkillsProject3={null} SkillsProject4={null} SkillsProject5={null} SiteProject={"https://www.figma.com/proto/xTlHWvVD1gmziJAV7DYLoi/Atividade07?type=design&node-id=1-2&t=JnHSn6XSNtisCdG1-0&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A2"} GithubProject={null} GithubProject2={null} FigmaProject={"https://www.figma.com/file/xTlHWvVD1gmziJAV7DYLoi/Atividade07?type=design&node-id=0%3A1&mode=design&t=JnHSn6XSNtisCdG1-1"}/>
            <ProjectBox ImgProject={"projeto-filmes.png"} NameProject={"App de cinema"} DescriptionProject={"Neste projeto, você pode escolher o filme desejado, ler uma descrição dele, além de optar por dia, horário etc. Com suas preferências, você pode fazer a compra."} SkillsProject1={null} SkillsProject2={null} SkillsProject3={null} SkillsProject4={null} SkillsProject5={null} SiteProject={"https://www.figma.com/proto/yg9wVubUzTHERZLcebsje9/Atividade03?type=design&node-id=0-1786&t=Jt9GzPMUWZMjgfZP-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=0%3A1786"} GithubProject={null} GithubProject2={null} FigmaProject={"https://www.figma.com/file/yg9wVubUzTHERZLcebsje9/Atividade03?type=design&node-id=0%3A1&mode=design&t=Jt9GzPMUWZMjgfZP-1"}/>
            <ProjectBox ImgProject={"projeto-petshop.png"} NameProject={"Petshop"} DescriptionProject={"Aqui, podemos observar uma landing page de um petshop, onde as cores e elementos são colocados de uma forma suave e bem organizada."} SkillsProject1={null} SkillsProject2={null} SkillsProject3={null} SkillsProject4={null} SkillsProject5={null} SiteProject={"https://www.figma.com/proto/HFeLT8s0lWcGM6xjI7KIpN/Atividade05?type=design&node-id=5-2&t=I5VOezEURJ5QX8wG-0&scaling=min-zoom&page-id=0%3A1"} GithubProject={null} GithubProject2={null} FigmaProject={"https://www.figma.com/file/HFeLT8s0lWcGM6xjI7KIpN/Atividade05?type=design&node-id=0%3A1&mode=design&t=I5VOezEURJ5QX8wG-1"}/>
            </div>
            </section>
            <div className="fixed-icon" onClick={toggleTheme} style={{ background: theme.NavBackground }}><img src="icon-moon-sun.svg" alt="icone de sol e lua" width="30px"></img></div>
        </div>
    )
}

export default AllProjects